# Generated by Django 3.2.7 on 2021-10-01 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField(unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('description', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('RA', models.DecimalField(decimal_places=4, max_digits=9)),
                ('DEC', models.DecimalField(decimal_places=4, max_digits=9)),
                ('ztf_name', models.CharField(max_length=255)),
                ('source_class', models.CharField(choices=[('TDE', 'TDE Source'), ('NOT_TDE', 'Not TDE Source'), ('NaN', 'Unknown Source')], default='NaN', max_length=20)),
                ('id_in_survey', models.PositiveIntegerField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='surveys.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=4000)),
                ('follow_up', models.TextField(max_length=2000)),
                ('edit_at', models.DateTimeField(auto_now_add=True)),
                ('edit_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='surveys.source')),
            ],
        ),
    ]
