# Generated by Django 3.2.7 on 2021-10-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='id_in_survey',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
