# Generated by Django 3.2.7 on 2021-10-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20211001_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='id_in_survey',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_class',
            field=models.CharField(blank=True, choices=[('TDE', 'TDE Source'), ('NOT_TDE', 'Not TDE Source'), ('NaN', 'Unknown Source')], default='NaN', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='ztf_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
