# Generated by Django 3.2.7 on 2021-10-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20211002_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
