# Generated by Django 3.2.7 on 2021-10-02 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='surveys.survey'),
        ),
    ]
