# Generated by Django 3.2.7 on 2021-10-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20211003_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='source',
        ),
        migrations.AddField(
            model_name='comment',
            name='source_class',
            field=models.CharField(blank=True, choices=[('TDE', 'TDE Source'), ('NOT_TDE', 'Not TDE Source'), ('NaN', 'Unknown Source')], default='NaN', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='comment',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='gen_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='surveys.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='follow_up',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
