# Generated by Django 3.2.7 on 2021-10-06 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_auto_20211006_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='surveys.survey'),
        ),
    ]
