# Generated by Django 3.2.7 on 2021-10-11 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_auto_20211010_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_curve', models.CharField(blank=True, max_length=255, null=True)),
                ('spectrum', models.CharField(blank=True, max_length=255, null=True)),
                ('trans', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='surveys.source')),
            ],
        ),
    ]
