# Generated by Django 3.2.7 on 2021-10-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
