# Generated by Django 3.2.7 on 2021-10-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_auto_20211027_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
