# Generated by Django 3.2.7 on 2021-11-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='B',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='CTS',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='EXP',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='FLUX',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='G_L_e2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='G_U_e2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='G_e2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='L',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='LIKE',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='NH_L_e2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='NH_U_e2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='NH_e2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='R98',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='RATIO_e2e1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='TSTART',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='TSTOP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='Tin_L_e2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='Tin_U_e2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='Tin_e2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='UPLIM',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='flag_agn_wise',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='flag_radio',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='flag_xray',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='g_d2d',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='g_gmag',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='g_nsrc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='g_s',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='s_d2d',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='s_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='s_otype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='s_z',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='sdss_nsrc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='sdss_p',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='w',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='w_nsrc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='w_snr',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='DEC',
            field=models.DecimalField(decimal_places=5, max_digits=9),
        ),
        migrations.AlterField(
            model_name='source',
            name='RA',
            field=models.DecimalField(decimal_places=5, max_digits=9),
        ),
        migrations.AlterField(
            model_name='source',
            name='ztf_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
