# Generated by Django 3.2.7 on 2021-11-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_auto_20211103_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
