# Generated by Django 3.2.7 on 2021-11-07 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_alter_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='prim_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='surveys.source'),
        ),
        migrations.AddField(
            model_name='source',
            name='primary',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
