# Generated by Django 3.2.7 on 2021-11-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_auto_20211107_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='master_source',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='prim_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='surveys.source'),
        ),
    ]
