# Generated by Django 3.2.7 on 2021-11-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_auto_20211107_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='master_source',
            field=models.BooleanField(blank=True, default=models.BooleanField(blank=True, default=True, null=True), null=True),
        ),
    ]
