# Generated by Django 3.2.7 on 2021-11-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_alter_source_master_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='CTS',
        ),
        migrations.RemoveField(
            model_name='source',
            name='EXP',
        ),
        migrations.RemoveField(
            model_name='source',
            name='FLUX',
        ),
        migrations.RemoveField(
            model_name='source',
            name='TSTART',
        ),
        migrations.RemoveField(
            model_name='source',
            name='TSTOP',
        ),
        migrations.RemoveField(
            model_name='source',
            name='UPLIM',
        ),
        migrations.RemoveField(
            model_name='source',
            name='prim_source',
        ),
        migrations.RemoveField(
            model_name='source',
            name='primary',
        ),
        migrations.RemoveField(
            model_name='source',
            name='w',
        ),
        migrations.RemoveField(
            model_name='source',
            name='w_snr',
        ),
        migrations.AddField(
            model_name='source',
            name='CTS_e1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='CTS_e2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='CTS_e3',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='EXP_e1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='EXP_e2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='EXP_e3',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='FLUX_e1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='FLUX_e2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='FLUX_e3',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='TSTART_e1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='TSTART_e2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='TSTART_e3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='TSTOP_e1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='TSTOP_e2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='TSTOP_e3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='UPLIM_e1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='UPLIM_e2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='UPLIM_e3',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='w_e1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='w_e2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='w_e3',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='w_snr_e1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='w_snr_e2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='w_snr_e3',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='master_source',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
