# Generated by Django 3.2.7 on 2021-11-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_auto_20211107_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='LIKE',
        ),
        migrations.AddField(
            model_name='source',
            name='LIKE_e1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='LIKE_e2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='LIKE_e3',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
    ]
