# Generated by Django 3.2.7 on 2021-11-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_auto_20211107_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='B',
        ),
        migrations.RemoveField(
            model_name='source',
            name='L',
        ),
        migrations.RemoveField(
            model_name='source',
            name='R98',
        ),
        migrations.RemoveField(
            model_name='source',
            name='g_d2d',
        ),
        migrations.RemoveField(
            model_name='source',
            name='g_gmag',
        ),
        migrations.RemoveField(
            model_name='source',
            name='g_nsrc',
        ),
        migrations.RemoveField(
            model_name='source',
            name='g_s',
        ),
        migrations.RemoveField(
            model_name='source',
            name='s_d2d',
        ),
        migrations.RemoveField(
            model_name='source',
            name='s_id',
        ),
        migrations.RemoveField(
            model_name='source',
            name='s_otype',
        ),
        migrations.RemoveField(
            model_name='source',
            name='s_z',
        ),
    ]
