# Generated by Django 3.2.7 on 2021-11-13 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0022_auto_20211113_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('RA', models.DecimalField(decimal_places=5, max_digits=9)),
                ('DEC', models.DecimalField(decimal_places=5, max_digits=9)),
                ('ztf_name', models.CharField(blank=True, max_length=100, null=True)),
                ('source_class', models.CharField(blank=True, choices=[('TDE', 'TDE Source'), ('NOT TDE', 'Not TDE Source'), ('NaN', 'Unknown Source')], default='NaN', max_length=20, null=True)),
                ('master_source', models.BooleanField(blank=True, default=False, null=True)),
                ('probable_source', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1500)),
                ('follow_up', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt_comments', to=settings.AUTH_USER_MODEL)),
                ('opt_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='surveys.optsource')),
            ],
        ),
    ]
