# Generated by Django 3.2.7 on 2021-11-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0025_auto_20211114_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='optsource',
            name='opt_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
