# Generated by Django 3.2.7 on 2021-11-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0026_optsource_opt_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optsource',
            old_name='ls_flux_w1',
            new_name='wise_flux_w1',
        ),
        migrations.RenameField(
            model_name='optsource',
            old_name='ls_flux_w2',
            new_name='wise_flux_w2',
        ),
        migrations.RenameField(
            model_name='optsource',
            old_name='ls_flux_w3',
            new_name='wise_flux_w3',
        ),
        migrations.RenameField(
            model_name='optsource',
            old_name='ls_flux_w4',
            new_name='wise_flux_w4',
        ),
    ]
