# Generated by Django 3.2.7 on 2021-11-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0029_auto_20211127_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='CTS_e1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='CTS_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='CTS_e3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='DEC',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='source',
            name='EXP_e1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='EXP_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='EXP_e3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='FLUX_e1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='FLUX_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='FLUX_e3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='G_L_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='G_U_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='G_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='LIKE_e1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='LIKE_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='LIKE_e3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='NH_L_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='NH_U_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='NH_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='RA',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='source',
            name='RATIO_e2e1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='Tin_L_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='Tin_U_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='Tin_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='UPLIM_e1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='UPLIM_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='UPLIM_e3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='flag_agn_wise',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='flag_radio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='flag_xray',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='sdss_nsrc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='sdss_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='w_e1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='w_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='w_e3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='w_nsrc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='w_snr_e1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='w_snr_e2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='w_snr_e3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
