# Generated by Django 3.2.7 on 2021-11-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0030_auto_20211127_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='row_num',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
