# Generated by Django 3.2.7 on 2021-12-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0031_source_row_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='w_e1',
        ),
        migrations.RemoveField(
            model_name='source',
            name='w_e2',
        ),
        migrations.RemoveField(
            model_name='source',
            name='w_e3',
        ),
        migrations.RemoveField(
            model_name='source',
            name='w_snr_e1',
        ),
        migrations.RemoveField(
            model_name='source',
            name='w_snr_e2',
        ),
        migrations.RemoveField(
            model_name='source',
            name='w_snr_e3',
        ),
    ]
